name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy react-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: CI= yarn prod
      - name: Firebase Install
        run: sudo npm install -g firebase-tools
      - name: Firebase Deploy
        run: firebase deploy --token ${{secrets.FIREBASE_TOKEN}}
